services:
  wk-node1:
    image: wukongim-dev:local
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./docker/conf/node1.conf:/etc/wukongim/wukongim.conf:ro
      - ./docker/dev-cluster/node1:/var/lib/wukongim
    ports:
      - "5001:5001"
      - "5100:5100"
      - "5200:5200"
      - "7100:7000"

  wk-node2:
    image: wukongim-dev:local
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./docker/conf/node2.conf:/etc/wukongim/wukongim.conf:ro
      - ./docker/dev-cluster/node2:/var/lib/wukongim
    ports:
      - "5002:5001"
      - "5101:5100"
      - "5201:5200"
      - "7001:7000"

  wk-node3:
    image: wukongim-dev:local
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./docker/conf/node3.conf:/etc/wukongim/wukongim.conf:ro
      - ./docker/dev-cluster/node3:/var/lib/wukongim
    ports:
      - "5003:5001"
      - "5102:5100"
      - "5202:5200"
      - "7002:7000"
